= Episode 1

:type: text,video
:tags: Java
:description: First episode with Product Architect, Leif Åstrand
:repo:
:linkattrs:
:imagesdir: ./images
:related_tutorials:

This is the first episode of Vaadin Coffee break, where we bring Vaadin experts, live, for the community to chat and ask all Vaadin related questions. In this episode, our guest is Leif Åstrand, the Product Architect at Vaadin. You can watch the full episode, and read the answers separately below especially those not answered during the session.

video::Dj9nd1_ZYsA[youtube]

== About the Expert

https://twitter.com/leifastrand[Leif] has been in product development for many years and has seen many things that can go wrong. As a product architect at Vaadin, he is now helping everyone else to prevent the mistakes that he has been part of making previously. He is helping out in everything around product development, like fixing challenging bugs, designing new features, and helping everyone else to develop the products.

== Worry About Backward Compatibility

====
_In the future is there a way not to worry about backward compatibility with Vaadin? -- Omar_
====

A consultant answer would be "it depends".
To give a better answer, we need to talk first about the web. The web as a platform is evolving quickly; there's no way around it. So things change all the time, like five years ago AngularJS was barely starting, but now it's not the most popular thing anymore. React has overtaken it, and Vue is getting up there. So things keep changing all the time.

Of course, you can still use Vaadin 6 if you want, we don't provide any security updates for free for it, but it works. It should work in all browsers, it works on relatively modern servers and so on. So if you have an application that just works, you can keep using it. However, if you want to benefit from all the new things, and make applications that look modern, that use the latest features from modern web browsers, then yes you need to make updates. Some of those updates require you to change more things because assumptions have changed, so it's really up to you.

We are giving quite good coverage there because when we released Vaadin 10, we said that it is getting support for five years to come. Looking at how quickly things evolve that's a long time still.

====
_We know that AngularJS was a nice experiment, and then quickly started to cause trouble for people who wanted to migrate to latest versions. So are we in the phase of AngularJS or the phase of top-notch Angular? -- A.Mahdy_
====

The plan that we have now is to add new things incrementally, we have one big thing upcoming which is to change from Polymer 2 to Polymer 3, and from the old deprecated Bower dependency management to NPM instead. That is going to be a significant change behind the scenes, but we try hard to make it smooth for users also. So we have now built a quite solid foundation to build upon it.

Again you can never know because things might change, but hopefully, this is a foundation that you can keep building on top of it.

One version that many are going to pick is 14, which is again a long-term support version, which means that we are going to support it for free for five years. Also with this version and all other versions, we provide non-free support for longer, but five years is what we give to everyone anywhere for free. Vaadin 14 has a scheduled release on June 2019.

== Run JavaEE and Spring Side by Side

====
_We are doing gradual migration from JavaEE to Spring. Both are running at the same time, and more code gets shipped to Spring in each subsequent minor release update. Where usually would be a good place to start the migration? -- Melvin_
====

The first step is to make sure that everything works when both stacks are running side by side — the next steps depend on your application structure. If you have independent services for different views, then you can make the view by view approach. Otherwise, you would have to go with layer by layer, start with service layer and then do a UI layer or vice versa. It's tough to give a generic answer without getting familiar with the application.

====
_The migration of the backend is independent on Vaadin, and if the backend is decoupled from the front-end, then Vaadin code is indifferent in this case, and view by view migration makes more sense -- A.Mahdy_
====

== Use Heat Map on Any Given Map

====
_I've seen people doing heat map on geographical maps like Google Maps, but I want to have a heat map on a floor map inside a building? -- Melvin_
====

TBC

== Portlet Support for Vaadin 10+
====
_Vaadin has had support for portlet (Liferay) development since version 6.  Does Vaadin 10+ support portlet development? -- Gordon_
====

We wanted to get Vaadin 10 out as quickly as possible, and we had to do lots of compromises, one of them that, yes, portlet support did not get implemented. Another thing that we didn't get done was CDI support for instance. CDI support became available in Vaadin 12, so a couple of releases afterward. Portlet support is still pending right now. We have a pile of customers for that, which probably means that by Vaadin 14 (beginning of June 2019), we could have portlet support. Plans might change, but 14 or maybe 15 is what it looks like right now.

====
_When you mention customers, how does it work to get certain features prioritized? Do they sponsor it? -- A.Mahdy_
====

It's case by case. Portlet support got sponsored, but generally, now and then customers have some specific feature that they can see on our list, but it's not on our top priority. But then they are eager to get it, so they sponsor the development of it.

There is always a sponsoring option for any feature that makes sense as a whole.

== Select Component in Vaadin 13

====
_I am using vaadin-spring-boot-starter 13.0.0.beta1 but can't use the Select component (there is no Select component) which should be available for Vaadin 13 as announced. What am I missing? -- Marco_
====

We had a bug in beta 1, and the Select component got included in two out of three places, and unfortunately the last critical place was missing. It is included in beta 2, which was out a week ago. So please update to beta 2, and you should have the Select component available there.

== Change Theme Dynamically

====
_How to change Vaadin theme dynamically? The user has a combobox filled with values (Lumo & Material), and on selection, the application should change the theme. -- Kaustubh_
====

In Vaadin 8, it's `UI.setTheme` so it should not be too complicated.
In Vaadin 10 and newer, and because the way we use specific browser features, like style encapsulation and CSS properties, it comes with a side effect that themes are pre-loaded in a way that makes it difficult to change it on the fly.

When you use the Lumo theme, you can configure many things by setting different CSS variables, that can be done just by adding and removing CSS, and get the theme changed on the fly.

Example, in your Vaadin application, apply a CSS style on the `<body>` element like:

[source,css]
----
--lumo-base-color: blue;
--lumo-font-size-m: 20px;
----

It gets updated on the fly. So just changing a couple of variables make quite significant changes. Again, this only work if the new theme is based on the Lumo theme. Enhancing this is still on the backlog, and it does not have a specific priority at the moment.

There is an add-on for https://vaadin.com/directory/component/cssvariablesetter[injecting CSS variables] that you can use to achieve those changes programmatically from Java code.


