[[flow.tutorial.form]]
= Creating a Form Using Plain Java

:title: Part 4 - Creating a Form Using Plain Java
:author: Vaadin
:description: Learn how to create a simple form with Vaadin Flow
:tags: Flow, Java
:imagesdir: ./images
:linkattrs:

In this part of the tutorial, we:

* Create a form using plain Java and connect it to the grid.
* Add functionality to add, update and delete customer data.

=== Creating the Form and Connecting It to the Grid

. Create a new class, `CustomerForm` that extends from `FormLayout`.
.. In Eclipse, right click on the "com.vaadin.starter.skeleton" package and choose "New > Class". Type in the name `CustomerForm`, define the superclass as `com.vaadin.flow.component.formlayout.FormLayout` and click `finish`.

. Edit `CustomerForm.java` and add the following:
.. Create two https://vaadin.com/components/vaadin-text-field[text] fields and a https://vaadin.com/components/vaadin-combo-box[combo box] field, by adding the following field declarations :
+
[source,java]
----
private TextField firstName = new TextField("First name");
private TextField lastName = new TextField("Last name");
private ComboBox<CustomerStatus> status = new ComboBox<>("Status");
private DatePicker birthDate = new DatePicker("Birthday");
----

.. Next add fields for the `Customer`, `CustomerService` and `MainView` and a basic constructor that accepts `MainView` as a parameter and adds the components to the layout:
+
[source,java]
----
private CustomerService service = CustomerService.getInstance();
private Customer customer;
private MainView mainView;

public CustomerForm(MainView mainView) {
    this.mainView = mainView;

    add(firstName, lastName, status, birthDate);
}
----
* We use these references later.

. In `MainView.java`:
.. Add the new form as a field:
+
[source,java]
----
private CustomerForm form = new CustomerForm(this);
----

.. Display the form, and wrap the `Grid` and `CustomerForm` in a horizontal layout, by replacing the `add(filtering, grid)` code line with:
+
[source,java]
----
HorizontalLayout main = new HorizontalLayout(grid, form);
main.setSizeFull();
grid.setSizeFull();

add(filtering, main);
----

. Save your code changes and refresh your browser. The main view now shows the form draft with four unconfigured fields to the right of the grid.

. In `CustomerForm.java`, add all enum values as options in the `ComboBox` field by adding the following line to the constructor:

+
[source,java]
----
status.setItems(CustomerStatus.values());
----
+


. In `CustomerForm.java`, we need a public API for the `MainView` to define which `Customer` to edit. We also use `Binder` for two-way data binding between the properties of the `Customer` and the UI fields in the form.
.. Add a `Binder` as a field:

+
[source,java]
----
private Binder<Customer> binder = new Binder<>(Customer.class);
----

* A `Binder` is an object that synchronizes the properties of domain objects to the UI fields. The binder takes care of reading values from the business object, and converts user data from the format expected by the field to that expected by the business object.


.. Configure the binder in the form constructor, by adding:
+
[source,java]
----
binder.bindInstanceFields(this);
----

* When using this method, the binder analyzes the bean and the form classes, and binds properties and fields with same names. For instance, the text field `firstName` is bound to the `Customer` property `firstName`. You can, of course, also do this manually.

.. Create a setter method for the customer field.

+
[source,java]
----
public void setCustomer(Customer customer) {
    this.customer = customer;
    binder.setBean(customer);
}
----

* This calls the `Binder.setBean` method that initializes all fields in the form and automatically updates the values in the domain objects as the corresponding field value changes in the UI

+
[NOTE]
As an alternative to naming-convention-based data binding, you can use the https://vaadin.com/api/platform/11.0.0/com/vaadin/flow/data/binder/PropertyId.html[`@PropertyId`] annotation on fields to explicitly declare the edited property.

. In `MainView.java`, connect the form to the grid, by adding the following selection listener at the end of the `MainView` constructor:

+
[source,java]
----
grid.asSingleSelect().addValueChangeListener(event -> {
    form.setCustomer(event.getValue());
});
----

* This listener simply takes the `Customer` object of the selected row and passes it to the `CustomerForm` for editing.

. At this point, your `CustomerForm` body code should be:

+
[source,java]
----
public class CustomerForm extends FormLayout {

    private TextField firstName = new TextField("First name");
    private TextField lastName = new TextField("Last name");
    private ComboBox<CustomerStatus> status = new ComboBox<>("Status");
    private DatePicker birthDate = new DatePicker("Birthday");

    private CustomerService service = CustomerService.getInstance();
    private Customer customer;
    private MainView mainView;

    private Binder<Customer> binder = new Binder<>(Customer.class);

    public CustomerForm(MainView mainView) {
        this.mainView = mainView;

        add(firstName, lastName, status, birthDate);

        status.setItems(CustomerStatus.values());

        binder.bindInstanceFields(this);
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
        binder.setBean(customer);
    }

}
----

. Save your code changes and refresh your browser to view the changes. When you select a row, the data is copied to the fields because the form is now "connected" to the grid.

=== Adding Save and Delete Buttons

In this part, we add functionality to update and delete `Customer` objects.

. In `CustomerForm.java`, add buttons as class variables:

+
[source,java]
----
private Button save = new Button("Save");
private Button delete = new Button("Delete");
----

. Add the buttons in a `HorizontalLayout` by adding following line to the constructor,

+
[source,java]
----
HorizontalLayout buttons = new HorizontalLayout(save, delete);
----

. Add the `buttons` object by amending the `add(firstName, lastName, status, birthDate)` code line to:

+
[source,java]
----
add(firstName, lastName, status, birthDate, buttons);
----

. Make the save button prominent, by decorating it with a style name:

+
[source,java]
----
save.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
----

* This improves the UI by highlighting the more common action.

. We also improve the user experience by hiding the form when it is not bound to a domain object, and focus the first name text field when a user is selected. Amend the `setCustomer` method to:

+
[source,java]
----
public void setCustomer(Customer customer) {
    this.customer = customer;
    binder.setBean(customer);
    boolean enabled = customer != null;
    setVisible(enabled);
    if (enabled) {
        firstName.focus();
    }
}
----

. To initialize the form state without an active customer, call `setCustomer(null)` at the end of the constructor.

+
[source,java]
----
setCustomer(null);
----
* This hides the form by default, until a `Customer` object is assigned to it.

. Add methods that will be called by the save and delete button click listeners in the next step.

+
[source,java]
----
private void delete() {
    service.delete(customer);
    mainView.updateList();
    setCustomer(null);
}

private void save() {
    service.save(customer);
    mainView.updateList();
    setCustomer(null);
}
----

. Add listeners to the buttons to call these methods by adding simple lambda expressions to the constructor:

+
[source,java]
----
save.addClickListener(e -> this.save());
delete.addClickListener(e -> this.delete());
----


. At this point, your `CustomerForm` body code should be:

+
[source,java]
----
public class CustomerForm extends FormLayout {

    private TextField firstName = new TextField("First name");
    private TextField lastName = new TextField("Last name");
    private ComboBox<CustomerStatus> status = new ComboBox<>("Status");
    private DatePicker birthDate = new DatePicker("Birthday");

    private CustomerService service = CustomerService.getInstance();
    private Customer customer;
    private MainView mainView;

    private Binder<Customer> binder = new Binder<>(Customer.class);

    private Button save = new Button("Save");
    private Button delete = new Button("Delete");

    public CustomerForm(MainView mainView) {
        this.mainView = mainView;

        HorizontalLayout buttons = new HorizontalLayout(save, delete);
        save.addThemeVariants(ButtonVariant.LUMO_PRIMARY);

        add(firstName, lastName, status, birthDate, buttons);

        status.setItems(CustomerStatus.values());

        binder.bindInstanceFields(this);

        setCustomer(null);

        save.addClickListener(e -> this.save());
        delete.addClickListener(e -> this.delete());

    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
        binder.setBean(customer);
        boolean enabled = customer != null;
        setVisible(enabled);
        if (enabled) {
            firstName.focus();
        }
    }

    private void delete() {
        service.delete(customer);
        mainView.updateList();
        setCustomer(null);
    }

    private void save() {
        service.save(customer);
        mainView.updateList();
        setCustomer(null);
    }

}
----

. Save your code changes and refresh your browser to view the changes. You can now edit and update current customer records.
+
[TIP]
For a truly re-usable form component in a real life project, you would want to introduce an interface to replace the `MainView` class. To keep things simple, we have not included this in the tutorial. As an even better alternative, you could use an event system like CDI events to completely decouple the components.

=== Adding New Customers

In this part, we add functionality in `MainView.java` to add new customer records. We create a new button, labeled *Add new customers*, above the grid next to the `filterText` field.

. Add a new `Button` with a click listener, by adding the following lines of code to the constructor, directly after `HorizontalLayout filtering = new HorizontalLayout...`:

+
[source,java]
----
Button addCustomerBtn = new Button("Add new customer");
addCustomerBtn.addClickListener(e -> {
    grid.asSingleSelect().clear();
    form.setCustomer(new Customer());
});
HorizontalLayout toolbar = new HorizontalLayout(filtering,
    addCustomerBtn);
----

* The click listener first clears a possible selection from the grid, then instantiates a new customer object, and then passes that to the form for editing.
* The `HorizontalLayout` creates a `toolbar` that includes both components next to the `filtering` composition.

. Add the toolbar by replacing the `add(filtering, grid);` code line with:
+
[source,java]
----
add(toolbar, main);
----

* The `filtering` composition was moved to the `toolbar` in the previous step.

. At this point:
.. Your `MainView` body code should be:
+
[source,java]
----
@Route("")
public class MainView extends VerticalLayout {

    private CustomerService service = CustomerService.getInstance();
    private Grid<Customer> grid = new Grid<>(Customer.class);
    private TextField filterText = new TextField();
    private CustomerForm form = new CustomerForm(this);

    public MainView() {

        filterText.setPlaceholder("Filter by name...");
        filterText.setValueChangeMode(ValueChangeMode.EAGER);
        filterText.addValueChangeListener(e -> updateList());

        Button clearFilterTextBtn = new Button(VaadinIcon.CLOSE_CIRCLE.create());
        clearFilterTextBtn.addClickListener(e -> filterText.clear());
        HorizontalLayout filtering = new HorizontalLayout(filterText, clearFilterTextBtn);

        Button addCustomerBtn = new Button("Add new customer");
        addCustomerBtn.addClickListener(e -> {
            grid.asSingleSelect().clear();
            form.setCustomer(new Customer());
        });
        HorizontalLayout toolbar = new HorizontalLayout(filtering,
            addCustomerBtn);

        // limit and define the order of properties shown by Grid
        grid.setColumns("firstName", "lastName", "status");

        HorizontalLayout main = new HorizontalLayout(grid, form);
        main.setSizeFull();
        grid.setSizeFull();

        add(toolbar, main);

        // make layout use full height (and grid expand to consume it)
        setSizeFull();

        updateList();

        grid.asSingleSelect().addValueChangeListener(event -> {
            form.setCustomer(event.getValue());
        });

    }

    public void updateList() {
        grid.setItems(service.findAll(filterText.getValue()));
    }

}
----

. Save your code changes and refresh your browser to view the changes.
Users can now create customer records that are stored in the demo backend.

Well done! You have just created your first app with Vaadin Flow.

== Next Steps

The next step is to use your new skills to create UIs for your existing Java apps or to create a completely new application. Here are a few resources to get you started:

* https://vaadin.com/start#vaadin10[Vaadin app starters^] - Explore the various starter packs.
* http://spring.io/guides/gs/crud-with-vaadin/[Creating CRUD UI with Vaadin^] - Another Vaadin tutorial with Spring Boot and Spring Data JPA backend that allows you to connect your application to a real database.
* https://vaadin.com/tutorials[Vaadin tutorials] - Learn more about Vaadin and integrations with related technologies.
* http://vaadin.com/directory[Directory] - Contains many Vaadin add-ons.
