= Introduction, Goals and Project Base

:author: Paul Römer
:type: text
:tags: Spring, Spring Boot
:description: A small introduction of what you can expect from this tutorial, its goals and the initial setup
:repo: https://github.com/vaadin-learning-center/spring-secured-vaadin
:linkattrs:
:imagesdir: ./images

We got quite some requests in the forum on how to use Vaadin 10+ with Spring Security. We heard you, we will help you. But let's start with definition of "use": 
Since Vaadin 10 you all know that we also support Polymer templates besides the Java-only approach. That means we already have to discuss two different types of client side implementation. In addition we can use as much Spring Security as possible by submitting a form to the configured endpoint or a little less by hooking into Spring Security's authentication flow. Both have ups and downs we will eleborate.
After that we will go into the details and work with roles for finer grained security and will not only enable whole views but also components depending on the logged in user. Last but not least we will introduce the addon ILAY that simplifies our task in securing the app.

In sum we end up with:
. Configuring Spring Security
. Setting up the login view (Java and Polymer based)
. Submitting the form vs. hooking into the authentication flow
. Finer grained security with roles on view and component level
. ILAY

Important to know is that basic knowledge of Vaadin 10+ and Spring Security and Spring Boot is required for this tutorial. We will _not_ discuss styling, production builds or other security unrelated stuff. It's the functionality we are focusing on.

== Get the base Vaadin + Spring starter
We are using https://vaadin.com/start/latest/project-base-spring as our starting point. At the time of writing the starter is using Vaadin 12.0.4 with Spring Boot 2.1.0.RELEASE.

```
.
├── LICENSE.md
├── pom.xml
├── README.md
├── src
│   └── main
│       ├── java
│       │   └── org
│       │       └── vaadin
│       │           └── paul
│       │               └── spring
│       │                   ├── Application.java
│       │                   ├── MainView.java
│       │                   └── MessageBean.java
│       └── resources
│           ├── application.properties
│           ├── banner.txt
│           └── META-INF
│               └── resources
│                   ├── frontend
│                   │   ├── src
│                   │   │   └── README
│                   │   └── styles
│                   │       └── README
│                   └── icons
│                       └── icon.png
```
The project setup is very minimalistic: single Maven module, no styles, no Polymer templates (prepared folder structure), the typical SpringBoot `Application` class and the main view. Because this starter showcases Spring it includes a message bean that is used injected and used in the `MainView`.

Now, run `mvn spring-boot:run` to build and start the web application.

Congrats!
