= Deploy to Heroku Cloud

:title: Deploy to Heroku Cloud
:authors: amahdy
:type: text
:tags: Backend, Cloud, Deploy, Flow, Java
:description: Learn how to deploy Java app to Heroku cloud
:repo:
:linkattrs:
:imagesdir: ./images

This tutorial shows how to deploy a Vaadin web application to Heroku cloud. We're using the latest https://vaadin.com/start/latest[Spring Boot starter app] as an example. You can see the app running on Heroku cloud https://starter-vaadin.herokuapp.com/[here].

The tutorial shows how an app can be deployed:

. As a `.jar` file
. As a `.war` file
. Directly from *GitHub*.

== Deploying a JAR file

A *JAR* (Java ARchive) is a package file that merges Java class files and assiociated metadata and resources, such as text and images, into one distributable file. This is the default format for the Spring Boot starter app.

. Create a Heroku account at https://www.heroku.com/home.
. Check if you have git installed by running the command `git --version` in your terminal. If no git version is found, download and install the https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[latest version] on your computer.
. Install https://devcenter.heroku.com/articles/heroku-cli#download-and-install[Heroku CLI] and login to your Heroku account.
. Install the Java CLI plugin by running the command `heroku plugins:install java` in your terminal.
. Download a starter project from http://vaadin.com/start/latest. Select *Spring Boot* as the Technology Stack and fill the *Maven Group ID* and *Project Name* as you see fit (or leave them at default).
. Change the `server.port` in your Spring project’s `application.properties` file (residing in src/main/resources) to: `server.port=${port:8080}`
. Generate a jar from your application using the maven goal `mvn package -Pproduction`
. Navigate to the folder with the generated `.jar`.
. Create a Heroku application by either:
.. Running `heroku create --no-remote` in the Java CLI plugin
.. By selecting *New* in the UI under https://dashboard.heroku.com/apps.
. Name the application. You will need the name in the next step.
. Deploy the `.jar` using the command: `heroku deploy:jar my-app.jar --app APP NAME`
. Run `heroku open --app APP NAME` or check the URL of the deployed app under *Domains*: https://dashboard.heroku.com/apps/APP_NAME/settings.

The demo is running as a JAR on Heroku at: https://starter-vaadin.herokuapp.com/

== Deploying a WAR file

A `.war` file is a Web Application Archive which runs inside an application server while a `.jar` is Java Application Archive that runs a desktop application on a user's machine. Deploying the app as a `.war` is done in the same way as a the previous `.jar` example with two exceptions:

. Change the package to from `.jar` to `.war` in the `pom.xml`
. The command to execute in step 11 is: `heroku war:deploy myapp.war --app APP_NAME`

Link to documentation: https://devcenter.heroku.com/articles/configuring-war-deployment-with-the-heroku-toolbelt[Configuring WAR Deployment with the Heroku CLI]

The demo is running as a WAR on Heroku at: https://starter-vaadin-war.herokuapp.com/

== Deploying from GitHub

You can deploy an application directly from GitHub, but two additional configuration files should be added for it to work: 

. Procfile
+
* Content:
+
`web: java -jar target/starter_app-2.0-SNAPSHOT.jar $PORT`
+
. heroku-settings.xml
* Content:
+
.`*pom.xml*`
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <!-- activate by setting the MAVEN_SETTINGS_PATH config var to heroku-settings.xml in Heroku project settings tab.
    See https://devcenter.heroku.com/articles/using-a-custom-maven-settings-xml for more details.
     -->

    <activeProfiles>
        <activeProfile>production</activeProfile>
        <activeProfile>npm</activeProfile>
    </activeProfiles>
</settings>
----
+
NOTE: If you are using a Vaadin version below version 14.2, apart from configuring Heroku itself, the *frontend-maven plugin* should be used to download node. It’s better to configure it as a separate profile in the `pom.xml` of the project (Frontend-maven-plugin.) Starting from Vaadin 14.2, npm is downloaded automatically.

You can find the source code on https://github.com/mvysny/vaadin14-embedded-jetty#heroku-integration[GitHub].

The demo is running at: https://github.com/anasmi/herokuTest

_Co-authored by Anastasia Smirnova and Mikael Sukoinen_