= HelloWorld - with RedHat Undertow - Ramp up in a second

:type: text, video
:tags: RedHat, Undertow, Flow, Java
:description: How to start a Vaadin Flow project with RedHat Undertow in a second
:repo: https://github.com/vaadin-learning-center/flow-helloworld-maven-undertow
:linkattrs:
:imagesdir: ./images


A nano project to start a Vaadin project. Perfect for Micro-UIs packed as fat jar in a docker image.
This will be used in some of the tutorial implementations.

== Target of this project

The target of this project is a minimal ramp-up time for a first hello world.
Why we need one more HelloWorld? Well, the answer is quite easy.
If you have to try something out, or you want to make a small POC present something,
there is no time and budget to create a demo project.
You don't want to copy paste all small things together.
Here you will get a HelloWorld-Project that will give you all in a second.

Clone the repo and start editing the class `VaadinApp` or `CoreUIService`.
Nothing more. 

== How does it work?

This project will not use any additional maven plugin or technology.

Here we are using the plain *undertow* as Servlet-Container.
https://github.com/undertow-io/undertow[https://github.com/undertow-io/undertow]

But let's start from the beginning.

== Start the Servlet-Container (Java)

The class `CoreUIService` will ramp up the Container.

Here all the basic stuff is done. The start will init. a ServletContainer at port `8080`.
The WebApp will be deployed as `ROOT.war`. The following code will show how to ramp up an Undertow
from scratch.

[source,java]
----
  public void startup() {
    final ClassLoader classLoader = CoreUIService.class.getClassLoader();
    DeploymentInfo servletBuilder
        = Servlets.deployment()
                  .setClassLoader(classLoader)
                  .setContextPath("/")
                  .setDeploymentName("ROOT.war")
                  .setDefaultEncoding("UTF-8")
                  .setResourceManager(new ClassPathResourceManager(classLoader, "META-INF/resources/"))
                  .addServletContainerInitializer(
                      new ServletContainerInitializerInfo(RouteRegistryInitializer.class ,
                                                          setOfRouteAnnotatedClasses())
                      )
                  .addListener(Servlets.listener(ServletDeployer.class));

    final DeploymentManager manager = Servlets
        .defaultContainer()
        .addDeployment(servletBuilder);
    manager.deploy();

    try {
      PathHandler path = path(redirect("/"))
          .addPrefixPath("/" , manager.start());
      Undertow u = Undertow.builder()
                           .addHttpListener(valueOf(getProperty(CORE_UI_SERVER_PORT ,
                                                                CORE_UI_SERVER_PORT_DEFAULT)) ,
                                            getProperty(CORE_UI_SERVER_HOST ,
                                                        CORE_UI_SERVER_HOST_DEFAULT)
                           )
                           .setHandler(path)
                           .build();
      u.start();

      u.getListenerInfo().forEach(e -> logger().info(e.toString()));

      undertow = success(u);
    } catch (ServletException e) {
      logger().warning(e.getMessage());
      undertow = failure(e.getMessage());
    }
  }
----

One important and Vaadin specific part of this code are listed below.

[source,java]
----
.setResourceManager(new new ClassPathResourceManager(classLoader, "META-INF/resources/"))
----

If you are using the core Undertow, the default ResourceManager is a dummy implementation.
This will to a few **404** if Vaadin Flow will try to load resources that are part of
a jar. To get this solved, we need to declare a prefix for the **ClassPathResourceManager**
The prefix is **"META-INF/resources/"**. This path is not needed for ServletContainer
that are implementing and actively using the Servlet Spec 4. You will find in chapter 4.6
the definition of this folder.

But if you need your own paths included, you can implement the interface ResourceManager.
As a sample you will find an implementation below. (or in the class **VaadinFlowResourceManager**)

[source,java]
----
  @Override
  public Resource getResource(final String path) throws IOException {
    String modPath = path;
    if (modPath.startsWith("/")) {
      modPath = path.substring(1);
    }
    if (modPath.startsWith("webjars")) {
      modPath = "META-INF/resources/" + modPath;
    }
    if (modPath.startsWith("VAADIN/static/client")) {
      modPath = "META-INF/resources/" + modPath;
    }
    final String realPath = prefix + modPath;
    final URL resource = classLoader.getResource(realPath);
    if (resource == null) {
      return null;
    } else {
      return new URLResource(resource , path);
    }
  }
----

After this, you can start the app invoking the main-method.

== The UI itself

The UI itself contains not so many elements. There is only a button you can click.
For every click, the counter will be increased.
The component will be registered under the root-path, based on the Annotation `@Route("")`
For more pieces of information about the routing itself have a look at
https://vaadin.com/docs/flow/routing/tutorial-routing-annotation.html[https://vaadin.com/docs/flow/routing/tutorial-routing-annotation.html]

[source,java]
----
@Route("")
public class VaadinApp extends Composite<Div> {

  private final Button         btnClickMe   = new Button("click me");
  private final Span           lbClickCount = new Span("0");
  private final VerticalLayout layout       = new VerticalLayout(btnClickMe, lbClickCount);

  private int clickcount = 0;

  public VaadinApp() {
    btnClickMe.addClickListener(event -> lbClickCount.setText(valueOf(++clickcount)));

    //set the main Component
    System.out.println("setting now the main ui content..");
    getContent().add(layout);

  }
}
----

Happy Coding.
