[[flow.tutorial.grid]]
== Listing Entities in a Grid

:title: Part 2 - Listing Entities in a Grid
:author: Vaadin
:sectnums:
:tags: Flow, Java
:imagesdir: ./images

In this part of the tutorial we cover how to display data in a grid in your UI.

== Adding Domain Objects

Before getting into actual Vaadin development, we add the necessary domain objects and a dummy backend. In a real-world application, you would most probably have something similar implemented with JPA and EJB, or a Spring-based service.

The first step is to copy three Java classes from GitHub and add them to your project. 
We will use these classes to when building the UI. 

Here is a list of the files to copy: 

* https://raw.githubusercontent.com/vaadin/tutorial/vaadin10%2B/src/main/java/com/vaadin/starter/skeleton/backend/CustomerStatus.java[`CustomerStatus.java`]: This is a simple enum class
* https://raw.githubusercontent.com/vaadin/tutorial/vaadin10%2B/src/main/java/com/vaadin/starter/skeleton/backend/Customer.java[`Customer.java`]: This this is the main domain object. It is the basic Java bean that we use in our example.
* https://raw.githubusercontent.com/vaadin/tutorial/vaadin10%2B/src/main/java/com/vaadin/starter/skeleton/backend/CustomerService.java[`CustomerService.java`]: This is a simple service class via which you can request and modify `Customer` instances. Think of this class as the entry point to the dummy database.

[TIP]
The fastest way to copy classes in Eclipse is to use your clipboard. In your browser, select the text content of the class and choose *Edit > Copy*. In *Project Explorer* in Eclipse, right-click `../[packagename]#com.vaadin.starter.skeleton.my-app#` in `Java Resources` and choose *Edit > Paste*. Eclipse is smart enough to automatically create a properly-named Java file for the class.

[NOTE]
The actual implementation of these classes is not relevant for this tutorial, but feel free to explore them.


=== Adding UI Code to Show Data in a Grid

When building a UI for a data-centric application, you would typically start by listing the data from your backend. Vaadin offers several components and ways to do this. In this example, we use the `Grid` component to present our customer data in tabular form. 

. Reference `CustomerService` and introduce a `Grid` field in [classname]`MainView.java`. 

+
[source, java]
----
@Route("")
public class MainView extends VerticalLayout {

    private CustomerService service = CustomerService.getInstance();
    private Grid<Customer> grid = new Grid<>(Customer.class);

    public MainView() {
----

[TIP]
If you are new to Java development, you probably do not feel comfortable with the red compilation error for the line where the [classname]#Grid# got introduced, because of a missing import. This is easily fixed in Eclipse by using the "Source > Organize Imports" command. Learn its shortcut (kbd:[Ctrl-Shift-O]		
 or kbd:[CMD-Shift-O] on Macs), you will be using it a lot in Java development. In possible class name collisions, always choose the appropriate class from the `com.vaadin.flow` package if you want to import core Vaadin Flow UI components, like the Grid.

. To list first name, last name and status properties of all `Customer` objects from the backend service, introduce a method `updateList` and replace the [classname]`MainView` constructor with:

+
[source,java]
----
public MainView() {

	// limit and define the order of properties shown by Grid
	grid.setColumns("firstName", "lastName", "status");

	add(grid);

	// make layout use full height (and grid expand to consume it)
	setSizeFull();
	
	updateList();
}

public void updateList() {
	grid.setItems(service.findAll());
}
----

. Save your code changes and refresh your browser to view the changes.  
