= Adding form based login views
:author: Paul Römer
:title: Adding form based login views
:type: text
:tags: Spring, Spring Boot
:description: Form based login views using only Java or Polymer templates
:repo: https://github.com/vaadin-learning-center/spring-secured-vaadin/branches
:linkattrs:
:imagesdir: ./images

Right now, our App is super secure. Too secure, in fact as you are not able to login at all. Time to add our first, form based, login views.

Even if form based login views feel kind of old-school nowadays, they have several advantages:
- nearly all security frameworks support them,
- ability to run frontend and backend on separate nodes,
- they are a well defined interface that allows us to change the underlying framework without (or with little) changes to the UI and
- in general you do not have to touch as much security related code as you would have to with other approaches (less code, less bugs).

The big disadvantage is the need for a page reload during the login which breaks the UX in modern Single Page Applications.

== Java-only 
As promised we will start with implementing a Java-only login view. Yes, I know. We cannot avoid all JS but we reduced it as much as possible.

First of all, we have to add `iron-form` that allows us to use HTML forms with custom elements. Just add the needed WEBJAR to your dependencies:
[source,xml]
----
<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>iron-form</artifactId>
    <version>2.4.0</version>
</dependency>
----

Second, we add a vertically layouted login view with all needed fields, forms and buttons:
[source,java,linenums]
----
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
@HtmlImport("frontend://bower_components/iron-form/iron-form.html") // <1>
public class LoginView extends VerticalLayout {
	public static final String ROUTE = "login";

	public LoginView() {
		TextField userNameTextField = new TextField();
		userNameTextField.getElement().setAttribute("name", "username"); // <2>
		PasswordField passwordField = new PasswordField();
		passwordField.getElement().setAttribute("name", "password"); // <3>
		Button submitButton = new Button("Login");
		submitButton.setId("submitbutton"); // <4>
		UI.getCurrent().getPage().executeJavaScript("document.getElementById('submitbutton').addEventListener('click', () => document.getElementById('ironform').submit());"); // <5>

		FormLayout formLayout = new FormLayout(); // <6>
		formLayout.add(userNameTextField, passwordField, submitButton);

		Element formElement = new Element("form"); // <7>
		formElement.setAttribute("method", "post");
		formElement.setAttribute("action", "login");
		formElement.appendChild(formLayout.getElement());

		Element ironForm = new Element("iron-form"); // <8>
		ironForm.setAttribute("id", "ironform");
		ironForm.setAttribute("allow-redirect", true); // <9>
		ironForm.appendChild(formElement);

		getElement().appendChild(ironForm); // <10>

		setClassName("login-view");
	}
}
----
<1> Tells Flow that we need iron forms for the frontend.
<2> Adds a Vaadin text field for username and sets the form name attribute.
<3> Same as above but for passwords using Vaadin password field.
<4> Creates a Vaadin button and makes it referencable by defining an `id`.
<5> Yeah, I know. JS. But we somehow have to register the `click` event with the `submit()` method of the `iron-form`.
<6> Adds a Vaadin form layout and adds all configured components.
<7> Creates a native `form` element, defines `method` and `action` of the form and appends the Vaadin form layout.
<8> Creates an `iron-form` that encapsulates the `form` element. Only that allows the use of Vaadin components (buttons and fields) in forms.
<9> Tells `iron-form` that we want to handle the redirect in the response.
<10> Finally, attaches everything to the UI.


== Polymer
Now the same form implemented with the help of Polymer templates. As in the Java-only example the `iron-form` component is needed to allow HTML forms with custom elements. Just add the needed WEBJAR to your dependencies:
[source,xml]
----
<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>iron-form</artifactId>
    <version>2.4.0</version>
</dependency>
----

The Java companion file just defines the route and references the Polymer template:
[source,java,linenums]
----
@Tag("sa-login-view")
@HtmlImport("frontend://src/views/sa-login-view.html")
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
public class LoginView extends PolymerTemplate<TemplateModel> {
	public static final String ROUTE = "login";
}
----

And finally the actual declaration of our login Polymer component:
[source,html,linenums]
----
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/polymer/lib/mixins/gesture-event-listeners.html">
<link rel="import" href="../../bower_components/iron-form/iron-form.html">
<link rel="import" href="../../bower_components/vaadin-button/vaadin-button.html">
<link rel="import" href="../../bower_components/vaadin-text-field/vaadin-text-field.html">
<link rel="import" href="../../bower_components/vaadin-text-field/vaadin-password-field.html">
<link rel="import" href="../../bower_components/vaadin-ordered-layout/vaadin-vertical-layout.html">

<dom-module id="sa-login-view">
    <template>
        <div class="container">
            <iron-form class="login" id="form" allow-redirect> <!-- <1> -->
                <form method="post" action="login"> <!-- <2> -->
                    <vaadin-vertical-layout>
                        <vaadin-text-field id="username" name="username" autofocus required></vaadin-text-field>
                        <vaadin-password-field id="password" name="password" required></vaadin-password-field>
                        <vaadin-button on-tap="login" theme="primary"> <!-- <3> -->
                            Login
                        </vaadin-button>
                    </vaadin-vertical-layout>
                </form>
            </iron-form>
        </div>
    </template>

    <script>
      class LoginView extends Polymer.GestureEventListeners(Polymer.Element) {
        static get is() {
          return 'sa-login-view';
        }

        login() { <!-- <4> -->
          if (!this.$.username.invalid && !this.$.password.invalid) {
            this.$.form.submit();
          }
        }
      }

      window.customElements.define(LoginView.is, LoginView);
    </script>
</dom-module>
----
<1> Declares the encapsulating `iron-form`, allows redirects and makes the form referenceable.
<2> Declares the actual HTML form and adds needed fields and button.
<3> The button calls some interceptor to allow adding custom stuff...
<4> Which in this case does some client side evaluation of the input before submitting the form

Both approaches will create a very simple login form allowing users to enter their credentials and to use the button to login to the application.

Try them by running `mvn spring-boot:run` and use the configured credentials user/password. When successful you will get redirected to the frontpage and the main view of the Vaadin + Spring starter shows up.

Congrats!

PS: You may have noticed that the series stops abruptly after this section. The main reason is that I have a very busy schedule but wanted to get out at least some content. On the other hand it is a good opportunity for you to discuss and prioritize other topics in the comment section below. Maybe the next three sections I am suggesting aren't as important for you as I would expect. Maybe you want to make me write about other Spring Security related stuff. I don't know, tell me!

