= Adding a form-based login view to a Vaadin application with Spring Security
:author: Paul Römer
:title: Adding form-based login views to a Vaadin application using Spring Security
:type: text
:tags: Spring, Spring Boot
:description: This tutorial covers adding a form-based login view to Vaadin applications, using Java or Polymer templates.
:repo: https://github.com/vaadin-learning-center/spring-secured-vaadin/branches
:linkattrs:
:imagesdir: ./images

Right now, our App is super secure. Too secure, in fact as you are not able to log in at all. Time to add our first, form-based, login views.

Even if form based login views feel kind of old-school nowadays, they have several advantages:
- nearly all security frameworks support them,
- ability to run frontend and backend on separate nodes,
- they are a well-defined interface that allows us to change the underlying framework without (or with little) changes to the UI and
- in general, you do not have to touch as much security-related code as you would have to with other approaches (less code, fewer bugs).

The big disadvantage is the need for a page reload during the login which breaks the UX in modern Single Page Applications.

[TIP]
With Vaadin 13 we introduce a dedicated login component boiling down the needed code to less than 7 lines. Check alternative 3 below.

== Alternative 1: Java-only
As promised we will start with implementing a Java-only login view. Yes, I know. We cannot avoid all JavaScript, but we reduced it as much as possible.

[TIP]
Check https://github.com/vaadin-learning-center/spring-secured-vaadin/tree/java-form for the sources.

First of all, we have to add `iron-form` that allows us to use HTML forms with custom elements. Just add the needed WEBJAR to your dependencies:
[source,xml]
----
<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>iron-form</artifactId>
    <version>2.4.0</version>
</dependency>
----

Second, we add a vertically layouted login view with all needed fields, forms and buttons:

.`*LoginView.java*`
[source,java,linenums]
----
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
@HtmlImport("frontend://bower_components/iron-form/iron-form.html") // <1>
public class LoginView extends VerticalLayout {
    public static final String ROUTE = "login";

    public LoginView() {
        TextField userNameTextField = new TextField();
        userNameTextField.getElement().setAttribute("name", "username"); // <2>
        PasswordField passwordField = new PasswordField();
        passwordField.getElement().setAttribute("name", "password"); // <3>
        Button submitButton = new Button("Login");
        submitButton.setId("submitbutton"); // <4>
        UI.getCurrent().getPage().executeJavaScript("document.getElementById('submitbutton').addEventListener('click', () => document.getElementById('ironform').submit());"); // <5>

        FormLayout formLayout = new FormLayout(); // <6>
        formLayout.add(userNameTextField, passwordField, submitButton);

        Element formElement = new Element("form"); // <7>
        formElement.setAttribute("method", "post");
        formElement.setAttribute("action", "login");
        formElement.appendChild(formLayout.getElement());

        Element ironForm = new Element("iron-form"); // <8>
        ironForm.setAttribute("id", "ironform");
        ironForm.setAttribute("allow-redirect", true); // <9>
        ironForm.appendChild(formElement);

        getElement().appendChild(ironForm); // <10>

        setClassName("login-view");
    }
}
----
<1> Tells Flow that we need iron forms for the frontend.
<2> Adds a Vaadin text field for username and sets the form name attribute.
<3> Same as above but for passwords using Vaadin password field.
<4> Creates a Vaadin button and makes it referencable by defining an `id`.
<5> Yeah, I know. JS. However, we somehow have to register the `click` event with the `submit()` method of the `iron-form`.
<6> Adds a Vaadin form layout and adds all configured components.
<7> Creates a native `form` element, defines `method` and `action` of the form and appends the Vaadin form layout.
<8> Creates an `iron-form` that encapsulates the `form` element. Only that allows the use of Vaadin components (buttons and fields) in forms.
<9> Tells `iron-form` that we want to handle the redirect in the response.
<10> Finally, attaches everything to the UI.


== Alternative 2: Declarative view with a Polymer template
If you prefer, you could also implement the login-form with a Polymer template. 

[TIP]
Check https://github.com/vaadin-learning-center/spring-secured-vaadin/tree/polymer-form for the sources.

As in the Java-only example, the `iron-form` component is needed to allow HTML forms with custom elements. Just add the needed WEBJAR to your dependencies:

[source,xml]
----
<dependency>
    <groupId>org.webjars.bowergithub.polymerelements</groupId>
    <artifactId>iron-form</artifactId>
    <version>2.4.0</version>
</dependency>
----

The Java companion file defines the route and references the Polymer template:
[source,java,linenums]
----
@Tag("sa-login-view")
@HtmlImport("frontend://src/views/sa-login-view.html")
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
public class LoginView extends PolymerTemplate<TemplateModel> {
    public static final String ROUTE = "login";
}
----

And finally the actual declaration of our login Polymer component:
[source,html,linenums]
----
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/polymer/lib/mixins/gesture-event-listeners.html">
<link rel="import" href="../../bower_components/iron-form/iron-form.html">
<link rel="import" href="../../bower_components/vaadin-button/vaadin-button.html">
<link rel="import" href="../../bower_components/vaadin-text-field/vaadin-text-field.html">
<link rel="import" href="../../bower_components/vaadin-text-field/vaadin-password-field.html">
<link rel="import" href="../../bower_components/vaadin-ordered-layout/vaadin-vertical-layout.html">

<dom-module id="sa-login-view">
    <template>
        <div class="container">
            <iron-form class="login" id="form" allow-redirect> <!-- <1> -->
                <form method="post" action="login"> <!-- <2> -->
                    <vaadin-vertical-layout>
                        <vaadin-text-field id="username" name="username" autofocus required></vaadin-text-field>
                        <vaadin-password-field id="password" name="password" required></vaadin-password-field>
                        <vaadin-button on-tap="login" theme="primary"> <!-- <3> -->
                            Login
                        </vaadin-button>
                    </vaadin-vertical-layout>
                </form>
            </iron-form>
        </div>
    </template>

    <script>
      class LoginView extends Polymer.GestureEventListeners(Polymer.Element) {
        static get is() {
          return 'sa-login-view';
        }

        login() { <!-- <4> -->
          if (!this.$.username.invalid && !this.$.password.invalid) {
            this.$.form.submit();
          }
        }
      }

      window.customElements.define(LoginView.is, LoginView);
    </script>
</dom-module>
----
<1> Declares the encapsulating `iron-form`, allows redirects and makes the form referenceable.
<2> Declares the actual HTML form and adds needed fields and button.
<3> The button calls some interceptor to allow adding custom stuff...
<4> Which in this case does some client side evaluation of the input before submitting the form

== Alternative 3: Java-only with LoginForm or LoginOverlay component
With the release of Vaadin 13 we now provide an extremely simplified way to get a login form via dedicated login components: The `LoginOverlay` component is a full-featured login dialog whereby `LoginForm` can be integrated wherever you need it. For details check the https://vaadin.com/components/vaadin-login[documentation, router-link=true].

[TIP]
Check https://github.com/vaadin-learning-center/spring-secured-vaadin/tree/login-overlay-form and https://github.com/vaadin-learning-center/spring-secured-vaadin/tree/login-component-form for the sources.

Using them boils down the whole `LoginView` to

[source,java,linenums]
----
@Tag("sa-login-view")
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
public class LoginView extends VerticalLayout {
        public static final String ROUTE = "login";

        private LoginOverlay login = new LoginOverlay(); // <1>

        public LoginView(){
            login.setAction("login"); // <2>
            login.setOpened(true); // <3>
            login.setTitle("Spring Secured Vaadin");
            login.setDescription("Login Overlay Example");
            getElement().appendChild(login.getElement()); // <4>
        }
}
----
<1> Gets the dialog.
<2> Sets the action aka the endpoint Spring Security is expecting the form data at.
<3> Opens the dialog immediately. Depending on your application behavior you can defer opening the dialog until some user interaction.
<4> Adds the form to the view.

[source,java,linenums]
----
@Tag("sa-login-view")
@Route(value = LoginView.ROUTE)
@PageTitle("Login")
public class LoginView extends VerticalLayout {
    public static final String ROUTE = "login";

    private LoginForm login = new LoginForm(); // <1>

    public LoginView(){
            login.setAction("login"); // <2>
            getElement().appendChild(login.getElement()); // <3>
    }
}
----
<1> Gets the form.
<2> Sets the action aka the endpoint Spring Security is expecting the form data at.
<3> Adds the form to the view.

Nice!

In sum, all presented approaches will create a straightforward login form allowing users to enter their credentials and to use a button to log in to the application in one or the other way.

Try them by running `mvn spring-boot:run` and use the configured credentials user/password. When successful, you will get redirected, and the main view of the Vaadin + Spring starter shows up.

Congrats!

[NOTE]
Check out the linked repository for implementation details. Each approach got its dedicated branch so you will find the code fitting your needs quite easily.

